### ISSUE TITLE
Switch to Github actions

### ISSUE THREAD

**Issue by ksuess** [plone/plone.app.blocks#84]

**Comment by MrTango** [comment]
When this is done and the build is green, i can make a release with the latest bugfix.

**Comment by mauritsvanrees** [comment]
I have just seen that we try to test on Travis with Plone 4.3, 5.1 and 5.2, but in fact all jobs use 5.2. In `.travis.yml` we do `sed -ie "s#test-x.x.x.cfg#test-$PLONE_VERSION.cfg#" buildout.cfg`. So we try to replace `test-x.x.x.cfg`. But in fact the buildout config does not contain this string, but only `test-5.2.x.cfg`. This is since commit 9eb351ae9fe45f572f49c63579a5da09b20a0e25, from almost two years ago. So currently we are not sure if the tests pass on 4.3 and 5.1. :-/

At Zest we are using the latest version 4.3.2 on a Plone 4.3 site with collective.cover, and that seems pretty stable.

But this could be a good time to call the next release 5.0.0 and support it only on Plone 5.2. Note that the changes since the last release only really matter on Python 3 or for Plone 5.2.

**Comment by thet** [comment]
Closed via: https://github.com/plone/plone.app.blocks/pull/89
